# Generated by Django 6.0.7 on 2026-07-18 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='CryptoInvest', max_length=100)),
                ('support_email', models.EmailField(default='support@cryptoinvest.local', max_length=254)),
                ('min_withdrawal', models.DecimalField(decimal_places=8, default=10, max_digits=18)),
                ('max_withdrawal', models.DecimalField(decimal_places=8, default=100000, max_digits=18)),
                ('referral_bonus_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('announcement', models.TextField(blank=True)),
                ('deposit_instructions', models.TextField(blank=True, default='Send the exact amount to the provided wallet address and submit your transaction hash.')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('email_verify', 'Email Verify'), ('2fa_enable', '2FA Enable'), ('2fa_disable', '2FA Disable'), ('kyc_submit', 'KYC Submit'), ('kyc_approve', 'KYC Approve'), ('kyc_reject', 'KYC Reject'), ('deposit_create', 'Deposit Create'), ('deposit_approve', 'Deposit Approve'), ('deposit_reject', 'Deposit Reject'), ('withdraw_create', 'Withdraw Create'), ('withdraw_approve', 'Withdraw Approve'), ('withdraw_reject', 'Withdraw Reject'), ('invest_create', 'Invest Create'), ('invest_complete', 'Invest Complete'), ('profile_update', 'Profile Update'), ('admin_action', 'Admin Action'), ('other', 'Other')], db_index=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'action'], name='core_auditl_created_2f8cb0_idx'), models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx')],
            },
        ),
    ]
