# Generated by Django 6.0.7 on 2026-07-18 12:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rate_to_usd', models.DecimalField(decimal_places=12, default=Decimal('1'), max_digits=24)),
                ('is_active', models.BooleanField(default=True)),
                ('symbol', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='maintenance_message',
            field=models.TextField(blank=True, default='We are performing scheduled maintenance. Please check back soon.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('email_verify', 'Email Verify'), ('2fa_enable', '2FA Enable'), ('2fa_disable', '2FA Disable'), ('kyc_submit', 'KYC Submit'), ('kyc_approve', 'KYC Approve'), ('kyc_reject', 'KYC Reject'), ('deposit_create', 'Deposit Create'), ('deposit_approve', 'Deposit Approve'), ('deposit_reject', 'Deposit Reject'), ('withdraw_create', 'Withdraw Create'), ('withdraw_approve', 'Withdraw Approve'), ('withdraw_reject', 'Withdraw Reject'), ('withdraw_paid', 'Withdraw Paid'), ('invest_create', 'Invest Create'), ('invest_complete', 'Invest Complete'), ('profile_update', 'Profile Update'), ('user_suspend', 'User Suspend'), ('user_activate', 'User Activate'), ('admin_action', 'Admin Action'), ('other', 'Other')], db_index=True, max_length=32),
        ),
    ]
