# Generated by Django 6.0.7 on 2026-07-18 13:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currencyrate_siteconfiguration_default_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default geo rules', max_length=100)),
                ('mode', models.CharField(choices=[('allow', 'Allow only listed'), ('block', 'Block listed')], default='block', max_length=10)),
                ('country_codes', models.TextField(blank=True, help_text='Comma-separated ISO codes e.g. US,CN,KP')),
                ('is_active', models.BooleanField(default=True)),
                ('block_message', models.CharField(default='Service is not available in your region.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('bonus_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('bonus_fixed', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('min_deposit', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(default='Terms of Service', max_length=200)),
                ('content', models.TextField()),
                ('is_current', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('min_total_invested', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('deposit_fee_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('withdrawal_fee_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('referral_bonus_boost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Extra % points added to referral commission', max_digits=6)),
                ('badge_color', models.CharField(default='#8B5CF6', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'VIP tier',
                'ordering': ['sort_order', 'min_total_invested'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, max_length=128)),
                ('events', models.CharField(default='deposit.approved,withdrawal.paid', help_text='Comma-separated event names', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='captcha_secret_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='captcha_site_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='live_chat_embed',
            field=models.TextField(blank=True, help_text='Optional Crisp/Intercom embed snippet'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='require_captcha_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='risk_disclaimer',
            field=models.TextField(blank=True, default='Cryptocurrency and investment products involve significant risk. Past or projected returns are not guaranteed. Only invest what you can afford to lose.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='withdrawal_sla_hours',
            field=models.PositiveIntegerField(default=24, help_text='Target hours to process withdrawals'),
        ),
        migrations.CreateModel(
            name='PlatformBackup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('target_price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('direction', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], default='above', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=64)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], default='hold', max_length=10)),
                ('entry_note', models.TextField(blank=True)),
                ('target', models.CharField(blank=True, max_length=100)),
                ('stop_loss', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('invested', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('profit', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('equity', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deposit_id', models.CharField(blank=True, max_length=64)),
                ('bonus_amount', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'promo'], name='core_promor_user_id_1fec35_idx')],
            },
        ),
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='core.termsversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'terms')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label', 'symbol'],
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
