# Generated by Django 6.0.7 on 2026-07-18 11:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('min_deposit', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_deposit', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('duration_days', models.PositiveIntegerField(help_text='Investment duration in days')),
                ('duration_flexible', models.BooleanField(default=False, help_text='If true, user can choose duration within min/max below')),
                ('min_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('max_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('profit_method', models.CharField(choices=[('pct_principal', 'Percentage of Principal'), ('fixed', 'Fixed Amount per Period'), ('compound', 'Compound Interest')], default='pct_principal', max_length=20)),
                ('return_percent_min', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Minimum expected return % over full duration', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('return_percent_max', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Maximum expected return % over full duration', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('profit_rate_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Profit % applied per payout period (or total if end-only)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fixed_profit_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Used when profit_method is fixed amount', max_digits=18)),
                ('payout_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('end', 'At Maturity Only')], default='daily', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('coming_soon', 'Coming Soon'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('allow_auto_reinvest', models.BooleanField(default=True)),
                ('allow_manual_reinvest', models.BooleanField(default=True)),
                ('return_principal', models.BooleanField(default=True, help_text='Return principal at maturity')),
                ('max_investments_per_user', models.PositiveIntegerField(blank=True, null=True)),
                ('total_invested', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('investors_count', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, default='bi-graph-up-arrow', max_length=50)),
                ('color', models.CharField(blank=True, default='#f0b90b', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('profit_rate_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('profit_method', models.CharField(max_length=20)),
                ('payout_frequency', models.CharField(max_length=20)),
                ('duration_days', models.PositiveIntegerField()),
                ('return_principal', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], db_index=True, default='active', max_length=20)),
                ('auto_reinvest', models.BooleanField(default=False)),
                ('total_earned', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('last_payout_at', models.DateTimeField(blank=True, null=True)),
                ('next_payout_at', models.DateTimeField(blank=True, null=True)),
                ('payouts_count', models.PositiveIntegerField(default=0)),
                ('expected_payouts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('matures_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.investmentplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reinvestment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('mode', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('new_investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinvestments_to', to='investments.investment')),
                ('source_investment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinvestments_from', to='investments.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinvestments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('period_number', models.PositiveIntegerField(default=1)),
                ('is_reinvested', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='investments.investment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='investments_user_id_14d02e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['status', 'next_payout_at'], name='investments_status_ab47ff_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_352b49_idx'),
        ),
    ]
