# Generated by Django 6.0.7 on 2026-07-18 13:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='early_exit_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='early_exit_penalty_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Penalty % of principal if user exits early', max_digits=6),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium plan (VIP Gold+ or KYC often required)'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='min_vip_slug',
            field=models.CharField(blank=True, help_text='Optional VIP tier slug required e.g. gold', max_length=50),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='require_kyc',
            field=models.BooleanField(default=False, help_text='Only KYC-verified users may invest in this plan'),
        ),
    ]
