# Generated by Django 6.0.7 on 2026-07-19 18:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investmentplan_early_exit_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='early_exit_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fee % if user exits before maturity', max_digits=6),
        ),
    ]
