# Generated by Django 6.0.7 on 2026-07-18 12:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Standard Referral', max_length=100)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Commission % of referred user deposit or investment', max_digits=6)),
                ('commission_on', models.CharField(choices=[('deposit', 'First Deposit'), ('investment', 'Each Investment'), ('profit', 'Profits')], default='deposit', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('min_deposit_for_commission', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('max_commission_per_referral', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
            ],
            options={
                'verbose_name': 'Referral Program',
            },
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('base_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(default='deposit', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_generated', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_earned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referrer', '-created_at'], name='referrals_r_referre_42bae3_idx'), models.Index(fields=['status', '-created_at'], name='referrals_r_status_9b5b28_idx')],
            },
        ),
    ]
