# Generated by Django 6.0.7 on 2026-07-18 13:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcommission',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = direct, 2–3 = upline'),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='level1_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='level2_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='level3_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='max_levels',
            field=models.PositiveSmallIntegerField(default=2, help_text='1–3 levels'),
        ),
    ]
