# Generated by Django 6.0.7 on 2026-07-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO country code', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='email_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tour_completed',
            field=models.BooleanField(default=False),
        ),
    ]
