# Generated by Django 6.0.7 on 2026-07-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_country_code_user_email_alerts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(default='USD', help_text='Display currency code: USD or crypto symbol e.g. BTC, USDT_TRC20', max_length=20),
        ),
    ]
