# Generated by Django 6.0.7 on 2026-07-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_preferred_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(blank=True, default='', help_text='Display crypto symbol (e.g. BTC, USDT_TRC20). Empty = last deposit crypto. Not USD by default.', max_length=20),
        ),
    ]
