# Generated by Django 6.0.7 on 2026-07-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_preferred_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='isp',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='timezone_name',
            field=models.CharField(blank=True, help_text='IANA timezone at access location', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone e.g. Africa/Kampala, detected from browser or login location', max_length=64),
        ),
    ]
