# Generated by Django 6.0.7 on 2026-07-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_social_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Remote avatar from Google/X when no uploaded picture is set', max_length=500),
        ),
    ]
