# Generated by Django 6.0.7 on 2026-07-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='auth_method',
            field=models.CharField(blank=True, default='password', help_text='password | google | x | unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='google_verified',
            field=models.BooleanField(default=False, help_text='Email verified via Google OAuth'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_method',
            field=models.CharField(blank=True, default='', help_text='password | google | x', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='login_alert_emails',
            field=models.BooleanField(default=True, help_text='Email me when a new login is detected'),
        ),
        migrations.AddField(
            model_name='user',
            name='public_bio',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='user',
            name='public_profile_enabled',
            field=models.BooleanField(default=False, help_text='Show public referral profile page'),
        ),
        migrations.AddField(
            model_name='user',
            name='require_social_reauth_withdraw',
            field=models.BooleanField(default=False, help_text='Require recent Google confirmation before withdrawals'),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_digest_emails',
            field=models.BooleanField(default=True, help_text='Weekly portfolio summary by email'),
        ),
    ]
