# Generated by Django 6.0.7 on 2026-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_social_security_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='require_social_reauth_withdraw',
            field=models.BooleanField(default=False, help_text='Require email code or Google confirmation before withdrawals'),
        ),
    ]
