# Generated by Django 6.0.7 on 2026-07-18 12:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Withdrawals'},
        ),
        migrations.AddField(
            model_name='deposit',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='transaction',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='transaction',
            name='network',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='credit_amount',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Balance credit after approval (defaults to amount − fee)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('profit', 'Profit'), ('referral', 'Referral'), ('reinvest', 'Reinvest'), ('refund', 'Refund'), ('fee', 'Fee'), ('adjustment', 'Adjustment')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='transaction_status_4b1739_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='transaction_referen_efec07_idx'),
        ),
    ]
