# Generated by Django 6.0.7 on 2026-07-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_withdrawal_options_deposit_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name_plural': 'Withdrawals'},
        ),
        migrations.AddField(
            model_name='deposit',
            name='promo_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Higher = process first (VIP)'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, help_text='Target time to complete withdrawal (admin SLA)', null=True),
        ),
    ]
