# Generated by Django 6.0.7 on 2026-07-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_withdrawal_options_deposit_promo_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='rate_usd',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='USD price of 1 unit of deposited crypto at approval', max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='credit_amount',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Platform credit in USD-equivalent after approval (crypto amount × rate)', max_digits=18, null=True),
        ),
    ]
