# Generated by Django 6.0.7 on 2026-07-18 11:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('network', models.CharField(choices=[('BTC', 'Bitcoin'), ('ERC20', 'Ethereum (ERC20)'), ('TRC20', 'Tron (TRC20)'), ('BEP20', 'BNB Smart Chain (BEP20)'), ('LTC', 'Litecoin')], max_length=20)),
                ('contract_address', models.CharField(blank=True, max_length=128)),
                ('decimals', models.PositiveSmallIntegerField(default=8)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or emoji', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('min_deposit', models.DecimalField(decimal_places=8, default=Decimal('0.001'), max_digits=18)),
                ('min_withdrawal', models.DecimalField(decimal_places=8, default=Decimal('10'), max_digits=18)),
                ('max_withdrawal', models.DecimalField(decimal_places=8, default=Decimal('100000'), max_digits=18)),
                ('withdrawal_fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('deposit_address', models.CharField(blank=True, max_length=256)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='wallet_qr/')),
            ],
            options={
                'verbose_name_plural': 'Cryptocurrencies',
                'ordering': ['sort_order', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('locked_balance', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Funds locked in active investments or pending withdrawals', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_deposited', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('total_withdrawn', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('total_profit', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('total_invested', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWalletAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=256)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to='wallets.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User wallet addresses',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'cryptocurrency', 'address')},
            },
        ),
        migrations.CreateModel(
            name='WalletLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('profit', 'Profit'), ('refund', 'Refund'), ('referral', 'Referral Bonus'), ('fee', 'Fee'), ('adjustment', 'Adjustment'), ('reinvest', 'Reinvest')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=8, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='wallets_wal_wallet__26c32b_idx'), models.Index(fields=['entry_type', '-created_at'], name='wallets_wal_entry_t_7a96b6_idx')],
            },
        ),
    ]
