# Generated by Django 6.0.7 on 2026-07-18 13:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='usd_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), help_text='Current price in USD used for balance display conversion', max_digits=24),
        ),
    ]
