from django.urls import path

from staffpanel import features, views

app_name = 'staffpanel'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('deposits/', views.deposit_list, name='deposits'),
    path('deposits/<uuid:pk>/approve/', views.deposit_approve, name='deposit_approve'),
    path('deposits/<uuid:pk>/reject/', views.deposit_reject, name='deposit_reject'),
    path('deposits/bulk-match/', features.bulk_deposit_match, name='bulk_match'),
    path('withdrawals/', views.withdrawal_list, name='withdrawals'),
    path('withdrawals/<uuid:pk>/approve/', views.withdrawal_approve, name='withdrawal_approve'),
    path('withdrawals/<uuid:pk>/paid/', views.withdrawal_paid, name='withdrawal_paid'),
    path('withdrawals/<uuid:pk>/reject/', views.withdrawal_reject, name='withdrawal_reject'),
    path('withdrawals/sla/', features.withdrawal_sla_queue, name='sla_queue'),
    path('treasury/', features.treasury, name='treasury'),
    path('risk/', features.risk_dashboard, name='risk'),
    path('compliance-export/', features.compliance_export, name='compliance_export'),
    path('backups/', features.backups, name='backups'),
    path('digest/', features.send_daily_digest, name='digest'),
    path('signals/', features.signals_admin, name='signals'),
    path('promos/', features.promos_admin, name='promos'),
    path('vip/', features.vip_admin, name='vip'),
    path('geo/', features.geo_admin, name='geo'),
    path('users/', views.user_list, name='users'),
    path('users/<int:pk>/', views.user_detail, name='user_detail'),
    path('users/<int:pk>/suspend/', views.user_suspend, name='user_suspend'),
    path('users/<int:pk>/activate/', views.user_activate, name='user_activate'),
    path('users/<int:pk>/verify-email/', views.user_verify_email, name='user_verify_email'),
    path('users/<int:pk>/unverify-email/', views.user_unverify_email, name='user_unverify_email'),
    path('kyc/', views.kyc_list, name='kyc'),
    path('kyc/<uuid:pk>/approve/', views.kyc_approve, name='kyc_approve'),
    path('kyc/<uuid:pk>/reject/', views.kyc_reject, name='kyc_reject'),
    path('plans/', views.plan_list, name='plans'),
    path('plans/new/', views.plan_edit, name='plan_new'),
    path('plans/<uuid:pk>/', views.plan_edit, name='plan_edit'),
    path('cryptos/', views.crypto_list, name='cryptos'),
    path('transactions/', views.transaction_list, name='transactions'),
    path('audit-logs/', views.audit_logs, name='audit_logs'),
    path('admin-activity/', views.admin_activity, name='admin_activity'),
    path('login-history/', views.login_history, name='login_history'),
    path('wallets/', views.wallets_overview, name='wallets'),
    path('referrals/', views.referrals_admin, name='referrals'),
    path('notifications/', views.notifications_center, name='notifications'),
    path('reports/', views.reports, name='reports'),
    path('settings/', views.settings_view, name='settings'),
    path('tickets/', views.tickets_list, name='tickets'),
    path('tickets/<uuid:pk>/', views.ticket_detail, name='ticket_detail'),
    path('cms/', views.cms_pages, name='cms'),
]
