# Generated by Django 6.0.7 on 2026-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('system', 'System'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('earning', 'Earning'), ('kyc', 'KYC'), ('security', 'Security'), ('referral', 'Referral'), ('announcement', 'Announcement')], default='system', max_length=20),
        ),
    ]
